### ISSUE TITLE
Player times out before joining any server

### ISSUE THREAD

**Issue by j5155** [GeyserMC/GeyserConnect#10]
Whenever I try to join a server through my locallly hosted geyserconnect, instead of joining the server, it times out after around 5 seconds. Looking at the logs while I'm joining shows geyserconnect beginning to start geyser, then the player timing out, then geyser starting after 10 seconds. This is probably caused by me not running it on the most powerful pc, but there should still be a way to not time the player out until geyser has actually started.

**Comment by rtm516** [comment]
I just pushed a change that should hopefully fix that.
https://github.com/GeyserMC/GeyserConnect/commit/5c439cb2a358db871be4c1bc88ac1e79c71b9a20
