### ISSUE TITLE
Suggestion: Allow all geyser config to be set

### ISSUE THREAD

**Issue by j5155** [GeyserMC/GeyserConnect#14]
It would be useful if we could change all of the geyser config in the geyserconnect config (outside of the server IP, port, and authentication options of course) so I could set whether I want to allow or deny optifine capes or allow building above the nether ceiling, and other options like that.

**Comment by CleMooling** [comment]
I agree with you and it's a pity that developers didn't notice this.

**Comment by j5155** [comment]
I mentioned it in the Discord actually and was told that it didn't really make sense when most use comes from one geyserconnect instance at geyserconnect.net
A while ago a beta geyserconnect instance became available which has the above nether ceiling feature I was really looking for.

**Comment by rtm516** [comment]
I plan on moving GeyserConnect to an extension for Geyser at some point which will allow all Geyser config options to be changed
