### ISSUE TITLE
Cannot connect to any server

### ISSUE THREAD

**Issue by Mio-sha512** [GeyserMC/GeyserConnect#2]
**Describe the bug**

When I click on a server it tries to connect but fails

**To Reproduce**

Download latest GeyserConnect version from Jenkins
Run It
Connect to it
Try and connect to CubeCraft
Fails

**Expected behavior**

I should connect with no problems  

**Screenshots / Videos**

Video: https://cdn.the-vlab.com/random/2020-06-23%2020-23-14.mp4

**Server Version**

What ever CubeCraft is using

**Geyser Version**

Geyser version 1.0-SNAPSHOT (git-master-effd760)
i have no idea what GeyserConnect version because it does not list that anyware (i guess build #4)

**Minecraft: Bedrock Edition Version**

Linux: 1.14.60 (running Local)
Minecraft Windows 10 Edition: 1.14.60 (running Local)
Mobile: 1.14.60

**Additional Context**

**Comment by rtm516** [comment]
You have likely configured/setup it wrong, I should be able to make a guide on how to use it and set it up along with a public instance in the next few days.

**Comment by rtm516** [comment]
Please see: https://github.com/GeyserMC/Geyser/wiki/GeyserConnect and contact me on [discord](http://discord.geysermc.org/) if you have any more issues.
