### ISSUE TITLE
Removing java version authentication

### ISSUE THREAD

**Issue by AndrewLugg** [GeyserMC/GeyserConnect#23]
Is there a way to disable java authentication on the docker/connect version? Geyser works fine for my Java servers, but I can't seem to find how to stop asking for Mojang credentials for for the docker/connect version.

**Comment by rtm516** [comment]
When you add a server there is an option for it.

**Comment by AndrewLugg** [comment]
Where is the option? there is no documentation or examples of it that I can find.

**Comment by rtm516** [comment]
Its a switch on the GUI when you add or edit a server, or use the `online` key to `false` in the config file for the server.

**Comment by AndrewLugg** [comment]
Thank you, it was the key `online` that I couldn't find, that worked perfectly. Thank you.
