### ISSUE TITLE
Java Account Storing

### ISSUE THREAD

**Issue by CrazyJannis44** [GeyserMC/GeyserConnect#25]
You could add the ability to store credential in the configs to a Bedrock username.
Like in the standalone version

**Comment by CrazyJannis44** [comment]
or generally make that the proxy config has any use

**Comment by GeekCornerGH** [comment]
I don't agree. Imagine, your host is hacked. Account storing require storing sensitive data. And I think you don't want to get your account used by someone that you don't know.

**Comment by CrazyJannis44** [comment]
then they should change it in the geyser standalone, spigot etc. to handle this consistently, but in my opinion they should add it to GeyserConnect. Ok they could mention a security warning, but some people use geyser connect with a vpn/in the local network

**Comment by rtm516** [comment]
Due to security concerns, this will not be added.

**Comment by Keksnet** [comment]
> I don't agree. Imagine, your host is hacked. Account storing require storing sensitive data. And I think you don't want to get your account used by someone that you don't know.

I see your point but **IF** your host is hacked you have a bigger problem and in the worst case every other of your accounts are compromised too

**Comment by Chew** [comment]
The decision has been made and the discussion is resolved. Please do not bump month-old issues.
