### ISSUE TITLE
server icon doesn't work correctly for long hostnames

### ISSUE THREAD

**Issue by creeper123123321** [GeyserMC/GeyserConnect#32]
It seems that mc-api.net sends incomplete hostname when it's too long, so VIAaaS addresses, which may be very long, doesn't show the icon

**Comment by rtm516** [comment]
Reported this to MC-API will close this when its resolved. If it cant be fixed by them ill add a workaround for hostnames longer than 45 characters.

**Comment by rtm516** [comment]
This has been resolved
