### ISSUE TITLE
Unable to locate Jar file?

### ISSUE THREAD

**Issue by PhilParr7** [GeyserMC/GeyserConnect#33]
![image](https://user-images.githubusercontent.com/70843928/121611686-ba7ed200-ca50-11eb-8a3f-cf485a0aa8ac.png)
this is the error in docker windows i think its because I'm on windows but I'm not sure

**Comment by rtm516** [comment]
You missed step 1
https://github.com/GeyserMC/GeyserConnect/tree/master/docker

**Comment by PhilParr7** [comment]
I have done that and it has that error data folder is located at : C:\Users\User\data

User is my account name
