### ISSUE TITLE
Geyser-Connect Starts and then restarts and continue on 

### ISSUE THREAD

**Issue by PhilParr7** [GeyserMC/GeyserConnect#34]
![image](https://user-images.githubusercontent.com/70843928/121671439-70c0d680-caa6-11eb-9d94-dc951425f090.png)
It will do that and my command to make the docker is `docker run --name "geyser-c" -d --restart always -p 19132:19132/udp -p 19133:19133/udp -v /data:/gsc geyser-connect `

**Comment by rtm516** [comment]
This is likely caused by docker being unable to mount the `/data` directory as it won't exist on windows so you will need to change it. If this is not the case then please provide a log and I will re-open this issue.

**Comment by PhilParr7** [comment]
![image](https://user-images.githubusercontent.com/70843928/121676368-73262f00-caac-11eb-8c1f-b49a30941fa8.png)
There isn't any logs in the log tab but have seen that

**Comment by PhilParr7** [comment]
![image](https://user-images.githubusercontent.com/70843928/121676903-1b3bf800-caad-11eb-8dc0-c33a409612d6.png)

Will not work on windows due to Java path being a Linux path sadly thanks for the help
