### ISSUE TITLE
Jar error on Linux - same starting and stopping

### ISSUE THREAD

**Issue by PhilParr7** [GeyserMC/GeyserConnect#36]
On Linux it is starting and stopping and also says the same Jar error could not find also where is the .jar to be and where can I get it from also bind9 doesn’t work due to file perms and accounts?

**Comment by rtm516** [comment]
Not sure what you mean, if you are trying to get geyser connect working please follow the instructions
Docker: https://github.com/GeyserMC/GeyserConnect/tree/master/docker
Bind9: https://github.com/GeyserMC/GeyserConnect/tree/master/bind9

**Comment by PhilParr7** [comment]
Docker will just start and stop on Linux 
And when I try bind9 i can’t put the files in to /etc/bind done to permissions on the account

**Comment by PhilParr7** [comment]
Kinda solved 

I didn’t use docker or the dns I when to Jenkins at: https://ci.opencollab.dev/job/GeyserMC/job/GeyserConnect/job/master/171/

and run the Jar file as a server and now it works

thanks for the  help :)
