### ISSUE TITLE
Suggestion: Use Floodgate Universally linked account instead of having to sign in... every single time

### ISSUE THREAD

**Issue by tschanadam** [GeyserMC/GeyserConnect#42]
I use a Nintendo Switch but I'm already linked so this saves a lot of time of having to dig out my phone open the link type the code log in and then go back to the switch, Also hard on my phone and ipad. thanks :)

**Comment by Konicai** [comment]
GeyserConnect *could* check if the Bedrock account is linked to a Java account, but the Global Api (which contains the global linking system), doesn't store user credentials (which would be a massive security risk), which puts that out if the question

The global linking system was designed as an extension of floodgate. i.e, bypass the authentication of the server, not store credentials for authentication

**Comment by Camotoy** [comment]
Yeah, this is something we don't plan on implementing, as we don't want to store credentials or authentication tokens remotely. Geyser standalone exists as an alternative where you can input your own code, or you can compile your own GeyserConnect and include your credentials in there.
Thanks anyway.
