### ISSUE TITLE
WHy does it not let me join hypixel when i sighn in to my microsoft acount

### ISSUE THREAD

**Issue by Ghostblade2981** [GeyserMC/GeyserConnect#44]
if any of youare have the same problem this is wierd it works for my  friends but not me

**Comment by lukeeey** [comment]
I really don't recommend you join Hypixel. There is a very good chance your account will get banned.

**Comment by rtm516** [comment]
GeyserConnect shouldnt block any server, if you are on about the unofficial public instance (geyserconnect.net) then its likely IP banned.
Please reply if its no the unofficial public instance

**Comment by Ghostblade2981** [comment]
i dont know

**Comment by Ghostblade2981** [comment]
> GeyserConnect shouldnt block any server, if you are on about the unofficial public instance (geyserconnect.net) then its likely IP banned.
> Please reply if its no the unofficial public instance

I dont know about that
