### ISSUE TITLE
Geyser Config passthrough

### ISSUE THREAD

**Issue by Greaper88** [GeyserMC/GeyserConnect#46]
Currently, only a very few config options can be changed on the imbedded Geyser. Is it reasonably possible to implement a system where the imbedded Geyser loads defaults unless a config option is specified? What I mean is, for example, if you leave "enable-extended-worldheight" out of the config, it'll default to false, but, if you place it in the config with "true," it'll pass that through and override the default.

I personally would like the extended-worldheight and above-nether-building passed through for an experimental server.

**Comment by rtm516** [comment]
No longer an issue as the rewrite moves it to a Geyser extension
