### ISSUE TITLE
The "Direct connect" menu can't be exited

### ISSUE THREAD

**Issue by EasyClifton** [GeyserMC/GeyserConnect#5]
**Issue overview**
The issue title basically explains it all, but I'm going to provide some more context below.

**Reproducing the issue**
Pressing the "Direct connect" button in the main menu of GeyserConnect will result in entering the Direct connect menu, which works as intended. The only exception is, that this menu cannot be exited if the "Submit" button was pressed while there wasn't anything in the "Adress" field. 
You can exit the menu via pressing the cross icon if you didn't press the "Submit" button while in the menu. But if you did, pressing the cross icon will close the Direct connect menu and instantly open it back up. This effectively soft-locks you on mobile devices (Its pretty hard to press the pause button while the menu is closed, because it re-opens very quickly.

**Videos/Screenshots**
https://streamable.com/v51oa4

**GeyserConnect build**
GeyserConnect build 7, powered by Geyser 252-253??

**Comment by rtm516** [comment]
Fixed with https://github.com/GeyserMC/GeyserConnect/commit/388502d
