### ISSUE TITLE
Make it possible to connect to a server using only one device.

### ISSUE THREAD

**Issue by makkarakka3** [GeyserMC/GeyserConnect#51]
I am on Ios and i run into a problem when trying to connect to a custom server. When i try to log in using a microsoft account it asks me to log in using a browser, but if i try to open a browser app and leave minecraft running in backround, minecraft kicks me out of the server so i cant connect with only my iphone, i have to use another device like my computer to complete login and not have minecraft kick me when switching apps. The mojang login does work when testing with my friends account, buti dont have a mojang mc account.

**Comment by turikhay** [comment]
Related to https://github.com/GeyserMC/Geyser/issues/2496

**Comment by rtm516** [comment]
Closing in favour of https://github.com/GeyserMC/Geyser/issues/2496 as mentioned since this isn't strictly a GeyserConnect issue
