### ISSUE TITLE
Login To Java Not Working

### ISSUE THREAD

**Issue by ghost** [GeyserMC/GeyserConnect#63]
When i Try To Login In To A Java Server I Do The Login and Click Done Then It just tells me that payed java account required even do i do have java through game pass and it did work yesterday can someone help?

**Comment by DBPT210** [comment]
I also have that problem. 
I just noticed that this issue exists for A MONTH?!? Sometime I wonder if the devs give a fuck.

**Comment by Camotoy** [comment]
Hello, a dev here.
I can assure you we do care about Geyser. See the changes we make here: https://github.com/GeyserMC/Geyser/commits/master
This bug is unfortunately harder to debug when I'm currently unable to replicate it myself. The unofficial GeyserConnect Discord has provided a potential workaround:
```
1. Go to Minecraft.net
2. Login
3. Press Change Skin
4. Set Profile Name (at the redeem page)
5. Refresh
6. If it let's you change your skin, It's good now. 
```

**Comment by DBPT210** [comment]
> Hello, a dev here.
> I can assure you we do care about Geyser. See the changes we make here: https://github.com/GeyserMC/Geyser/commits/master
> This bug is unfortunately harder to debug when I'm currently unable to replicate it myself. The unofficial GeyserConnect Discord has provided a potential workaround:
> ```
> 1. Go to Minecraft.net
> 2. Login
> 3. Press Change Skin
> 4. Set Profile Name (at the redeem page)
> 5. Refresh
> 6. If it let's you change your skin, It's good now. 
> ```

Oh OK. I understand.  I'm sorry for the inappropriate behavior.

**Comment by DBPT210** [comment]
Hello again, 
I tried to do the 4th step, but I can't seem to find any "Set Profile Name at the redeem page". If you could link me some sort of media tutorial I would gladly appreciate it.

**Comment by Camotoy** [comment]
I'm afraid I don't know of a picture source of those steps.
