### ISSUE TITLE
How I can enable nether roof building?

### ISSUE THREAD

**Issue by Dragon11-ui** [GeyserMC/GeyserConnect#73]
The title says it all, I can't find the option to enable nether roof building.

**Comment by onebeastchris** [comment]
It's "above-bedrock-nether-building" in the proxy_config.yml

**Comment by Dragon11-ui** [comment]
"proxy_config.yml" is missing.

**Comment by Dragon11-ui** [comment]
tried to clear my geyserconnect files, it doesn't generate "proxy_config.yml"

**Comment by onebeastchris** [comment]
My bad, I assumed it was generated - for some reason, it's not. However, that config does exist in the .jar file itself.. That's honestly odd why proxy_config is static otherwise

**Comment by Dragon11-ui** [comment]
tried enabling it, still doesn't work. It seems it doesn't use the "proxy_config.yml".

**Comment by onebeastchris** [comment]
https://github.com/GeyserMC/GeyserConnect/blob/master/src/main/java/org/geysermc/connect/proxy/GeyserProxyBootstrap.java#L69
that doesn't sound quite right though, seems like it reads it here 
If you want to edit it, I'd recommend to clone the project, and try setting the setting to "true" in src/.../resources/proxy_config.yml, and then building the jar. That should enable the setting.. probably. I should add that I haven't tried this myself

**Comment by Dragon11-ui** [comment]
That actually works! Thanks for the help!

**Comment by j5155** [comment]
For the future, the issues about a better way of doing this then rebuilding the jar from source are #14 and #46.
