### ISSUE TITLE
No main class in resulting jar file

### ISSUE THREAD

**Issue by stolencode** [GeyserMC/GeyserConnect#78]
If compiled as is, build results in a GeyserConnect.jar without a main class

**Comment by onebeastchris** [comment]
The new GeyserConnect jar isn't a standalone program, but a Geyser extension.
For usage, create a Geyser-Standalone server, with the GeyserConnect jar in the extensions folder - that way, you can use GeyserConnect like you're used to, but with more flexibility over Geyser related configuration

**Comment by stolencode** [comment]
Thanks for the clarification.  I'll try that.  Been a little while since i visited this project, I had a customer demo I was doing building the older maven build in a Tekton pipeline.  I'm going to have to do a little homework I guess
