### ISSUE TITLE
Crashing when joining on Bedrock 1.20.40

### ISSUE THREAD

**Issue by GeekCornerGH** [GeyserMC/GeyserConnect#79]
Hi everyone,

I'm trying to connect to a geyser-spigot server through GeyserConnect, and when joining the requested server, my game crashs.

* Minecraft Bedrock for Windows v1.20.40
* Geyser Dump on the GeyserConnect: [hmm, here](https://dump.geysermc.org/45Ft2B1XoNMu4U0wqDYDApzZO7lEpkJP)
* Geyser Dump on the backend server: [right here](https://dump.geysermc.org/h0YHJtRv32hcTowjtDgrLfIj9ohN1FSf)

Thanks in advance for your help

**Comment by hasankayra04** [comment]
Duplicate of #4240

**Comment by GeekCornerGH** [comment]
The interesting part is that logging in through the backend server geyser will work

**Comment by GeekCornerGH** [comment]
Seems it works now thanks
