### ISSUE TITLE
error when doing java -jar GeyserConnect.jar

### ISSUE THREAD

**Issue by DevX-77** [GeyserMC/GeyserConnect#87]
root ➜ /home/user/Downloads $ java -jar GeyserConnect.jar
no main manifest attribute, in GeyserConnect.jar
root ➜ /home/user/Downloads $

**Comment by Chew** [comment]
You don't run the jar directly, it's an extension to be used with a Geyser installation. See the wiki for a step-by-step guide: https://geysermc.org/wiki/other/geyserconnect

If you need help, feel free to ask us [on Discord](https://discord.gg/geysermc). Thank you!
