### ISSUE TITLE
GeyserConnect not showing motd

### ISSUE THREAD

**Issue by Dycool** [GeyserMC/GeyserConnect#9]
GeyserConnect does not show motd on both using dns or the server ip, but I can still join it.
![Screenshot_20200903_233013_com mojang minecraftpe](https://user-images.githubusercontent.com/65285981/92180091-1b340b00-ee3e-11ea-9e78-263e32a3b4ed.jpg)

**Comment by rtm516** [comment]
Can you provide more information about your setup? And is this still an issue?

**Comment by rtm516** [comment]
Inactive issue
